### PR TITLE
Let TLS clients pass the identity hint to the server

### LINKED ISSUE #4: Use with multiple PSKs
According to [./USAGE](https://github.com/bukka/pkcs11-proxy/blob/main/USAGE#L64):

> Currently, there is no way to specify the identity to use on the client side (client tells server what identity should be used), and the first identity found in the PSK file is used.
The server side will correctly look up the identity requested by the client in it's PSK file, so it is possible to have one unique PSK identity and key per PKCS11 client, and have all the identitys and keys in the PSK file for the PKCS11 daemon.

I have not managed to make this work with multiple keys; I think there's either an identity passing/communication issue, or a multiple-lines PSK file parsing issue on the server side.
## On the client
`/var/lib/pkcs11-proxy.psk`:
```
alfa:c11aae9359b7cb98ed56af5d2a3efd32
```

```bash
$ PKCS11_PROXY_SOCKET="tls://server:2345" PKCS11_PROXY_TLS_PSK_FILE="/var/lib/pkcs11-proxy.psk" pkcs11-tool --module=/usr/lib/libpkcs11-proxy.so -L
DEBUG: C_Initialize: enter
DEBUG: connecting to: tls://server:2345
DEBUG: Initialized TLS-PSK client
DEBUG: Initializing TLS-PSK with keyfile '/var/lib/pkcs11-proxy.psk', identity ''
DEBUG: Loaded TLS-PSK 'alfa' from keyfile '/var/lib/pkcs11-proxy.psk'
WARNING: can't start TLS : -1/6 (Success perhaps)
WARNING: SSL ERR: error:0A0003FC:SSL routines::ssl/tls alert bad record mac
WARNING: failed starting TLS
DEBUG: C_Initialize: 48
Main C_Initialize(NULL) rv:CKR_DEVICE_ERROR
DEBUG: C_Finalize: enter
WARNING: 'pkcs11_initialized' not true at rpc_C_Finalize
error: PKCS11 function C_Initialize failed: rv = CKR_DEVICE_ERROR (0x30)
Aborting.
```

## On the server:
`/var/lib/pkcs11-daemon/softhsm2.psk`:
```
softhsm2:33ab06e18f5d29d6a119f48145cf4772
alfa:c11aae9359b7cb98ed56af5d2a3efd32
```

Logs:

```logs
pkcs11-daemon[848449]: DEBUG: Initialized TLS-PSK server
pkcs11-daemon[848449]: Listening on: tls://[::]:2345
pkcs11-daemon[848449]: DEBUG: Initializing TLS-PSK with keyfile '/var/lib/pkcs11-daemon/softhsm2.psk', identity ''
pkcs11-daemon[848449]: DEBUG: Loaded TLS-PSK 'softhsm2' from keyfile '/var/lib/pkcs11-daemon/softhsm2.psk'
pkcs11-daemon[848449]: WARNING: can't start TLS : -1/1 (Success perhaps)
pkcs11-daemon[848449]: WARNING: SSL ERR: error:0A000119:SSL routines::decryption failed or bad record mac
pkcs11-daemon[848449]: WARNING: Can't enable TLS
```

It seems the `alfa` key is not seen, or understood by the server.

### PR DESCRIPTION
**Pull request by OdyX**
Probably not the ideal place to do this parsing, but it seems to make more sense than in the `_tls_psk_server_cb` function.

Happy to work on fixes!

Closes: https://github.com/bukka/pkcs11-proxy/issues/4

### CODE REVIEW

**Comment by bukka** [comment]
Thanks for the PR. I'm currently a bit busy but should have time in a week starting on 19th May so will take a proper look into this and other PR's then.

File: gck-rpc-tls-psk.c [hunk 1]
```diff
@@ -201,10 +200,29 @@ _tls_psk_client_cb(SSL *ssl, const char *hint,
 		   char *identity, unsigned int max_identity_len,
 		   unsigned char *psk, unsigned int max_psk_len)
 {
-	/* Client tells server which identity it wants to use in ClientKeyExchange */
-	snprintf(identity, max_identity_len, "%s", tls_psk_identity);
```
Comment (bukka) [inline gck-rpc-tls-psk.c]: I think it would be better to leave this part and do the parsing in `gck_rpc_init_tls_psk` - basically adding condition before that `snprintf(tls_psk_identity` line that would check if identity is NULL (which currently always is but we could potentially change it in the future) and do that parsing in such case.

**Review by bukka — COMMENTED** [review]
Overall I think this makes sense. Alternatively it would be also possible to add config field to the configuration file but this would be useful anyway and does the job without needing to use config file.

Added just a minor suggestion where to best move it.

File: gck-rpc-tls-psk.c (hunk 1 above)
Comment (OdyX) [reply gck-rpc-tls-psk.c]: Fair enough. I've force-pushed this change now.

**Review by bukka — CHANGES_REQUESTED** [review]
LGTM - I have done some testing and even checking with gdb that right identity gets set and it all works as expected. There is just a minor warning with snprintf but it's not a big issue  - will sort it out.

**Review by bukka — APPROVED** [review]

**Comment by bukka** [comment]
Accidentally requested changes but meant to just approve it :)
